version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tizim_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: normativ_tizim
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tizim_backend
    env_file:
      - ./backend/.env
    ports:
      - "5050:5000"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - backend_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tizim_frontend
    ports:
      - "8050:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  backend_data:
